name: Dupe
version: '1.0-SNAPSHOT'
main: org.ValkSteal.dupe.Dupe
api-version: '1.20'

commands:
  dupe:
    description: Executes the dupe command.
    usage: /dupe
    permission: Dupe.Command.Dupe
    permission-message: ยง4You do not have permission to execute this command.

permissions:
  Dupe.Command.Dupe:
    description: Allows the user to use the dupe command
    default: true
