name: Dupe
version: '1.0-SNAPSHOT'
main: org.ValkSteal.dupe.Dupe
api-version: '1.21'

commands:
  dupe:
    description: Executes the dupe command.
    usage: /dupe
    permission: dupe.command.dupe
    permission-message: You do not have permission to execute this command.
  blacklist:
    description: Executes the blacklist command.
    usage: /blacklist
    permission: dupe.command.blacklist
    permission-message: You do not have permission to execute this command.
permissions:
  dupe.command.dupe:
    description: Allows the user to use the dupe command
    default: op
  dupe.command.blacklist:
    description: Allows the user to add an Item to the dupe BlackList
    default: true