name: Java Build with Maven

on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install --batch-mode --no-transfer-progress -T 1C
      # --batch-mode: Minimizes output for faster processing
      # -T 1C: Uses 1 thread per available CPU core for parallel builds

    - name: Run tests
      run: mvn test --batch-mode --no-transfer-progress

    - name: Package and release
      if: success() # Only proceed if previous steps succeed
      run: mvn package --batch-mode --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload package
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: java-build-package
        path: target/*.jar
