name: Java Maven Testing

on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build the project
      run: mvn clean install --batch-mode --no-transfer-progress -T 1C

    - name: Run tests
      run: mvn test --batch-mode --no-transfer-progress
